<?php

namespace CCI\RamScoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ActiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActiviteRepository extends EntityRepository
{
}
