accueil:
    path: /
    defaults: { _controller: CCIRamScoBundle:Yasmina:indexPerso}

contact:
    path: contact
    defaults: { _controller: CCIRamScoBundle:Yasmina:contact }
    
ramassage:
    path: ramassage
    defaults: { _controller: CCIRamScoBundle:Yasmina:ramassage }

FARYM:
    path: farym
    defaults: { _controller: CCIRamScoBundle:Yasmina:farym }
    
    
    

register:
    path: register
    defaults: { _controller: FOSUserBundle:Registration:register}
    
profil:
    path: profile
    defaults: { _controller: FOSUserBundle:Profile:show }
    
profil_edit:
    path: profile/edit/{id}
    defaults: { _controller: CCIRamScoBundle:Yasmina:editprofil }
    
adherent:    
    path: adherent
    defaults: { _controller: CCIRamScoBundle:Yasmina:adherent }

    

admin:
    path: admin/
    defaults: { _controller: CCIRamScoBundle:Yasmina:admin }
 
    
    
participant_add:    
    path: admin/participant/add
    defaults: { _controller: CCIRamScoBundle:Yasmina:editparticipant }

participant_edit:    
    path: admin/participant/edit/{id}
    defaults: { _controller: CCIRamScoBundle:Yasmina:editparticipant }
    requirements : 
        id: \d+
        
participant_view:
    path: admin/participant/{id}
    defaults: { _controller: CCIRamScoBundle:Yasmina:ficheparticipant }
    requirements : 
        id: \d+


role_add:    
    path: admin/role/add
    defaults: { _controller: CCIRamScoBundle:Yasmina:editrole }
    
role_edit:    
    path: admin/role/edit/{id}
    defaults: { _controller: CCIRamScoBundle:Yasmina:editrole }
    requirements : 
        id: \d+
        
role_view:
    path: admin/role/{id}
    defaults: { _controller: CCIRamScoBundle:Yasmina:ficherole }
    requirements : 
        id: \d+
    
    
    
activite_add:    
    path: admin/activite/add
    defaults: { _controller: CCIRamScoBundle:Yasmina:editactivite }
    
activite_edit:    
    path: admin/activite/edit/{id}
    defaults: { _controller: CCIRamScoBundle:Yasmina:editactivite }
    requirements : 
        id: \d+
           
activite_view:
    path: admin/activite/{id}
    defaults: { _controller: CCIRamScoBundle:Yasmina:ficheactivite }
    requirements : 
        id: \d+







