accueil:
    path: /
    defaults: { _controller: CCIRamScoBundle:Yasmina:indexPerso}

contact:
    path: contact
    defaults: { _controller: CCIRamScoBundle:Yasmina:contact }
    
ramassage:
    path: ramassage
    defaults: { _controller: CCIRamScoBundle:Yasmina:ramassage }

FARYM:
    path: farym
    defaults: { _controller: CCIRamScoBundle:Yasmina:farym }
    
    
    

register:
    path: register
    defaults: { _controller: FOSUserBundle:Registration:register}
    
profil:
    path: profile
    defaults: { _controller: FOSUserBundle:Profile:show }
    
adherent:    
    path: adherent
    defaults: { _controller: CCIRamScoBundle:Yasmina:adherent }

    

admin:
    path: admin/
    defaults: { _controller: CCIRamScoBundle:Yasmina:admin }
 
    
    
participant_add:    
    path: admin/participant/add
    defaults: { _controller: CCIRamScoBundle:Yasmina:addparticipant }
        
participant_view:
    path: admin/participant/{id}
    defaults: { _controller: CCIRamScoBundle:Yasmina:ficheparticipant }



role_add:    
    path: admin/role/add
    defaults: { _controller: CCIRamScoBundle:Yasmina:addrole }
        
role_view:
    path: admin/role/{id}
    defaults: { _controller: CCIRamScoBundle:Yasmina:ficherole }
    
    
    
activite_add:    
    path: admin/activite/add
    defaults: { _controller: CCIRamScoBundle:Yasmina:addactivite }
           
activite_view:
    path: admin/activite/{id}
    defaults: { _controller: CCIRamScoBundle:Yasmina:ficheactivite }
    requirements : 
        id: \d+







