accueil:
    path: accueil
    defaults: { _controller: CCIRamScoBundle:Yasmina:indexPerso}

contact:
    path: contact
    defaults: { _controller: CCIRamScoBundle:Yasmina:contact }

FARYM:
    path: farym
    defaults: { _controller: CCIRamScoBundle:Yasmina:farym }
    
    

register:
    path: register
    defaults: { _controller: FOSUserBundle:Registration:register}
    
profil:
    path: profile
    defaults: { _controller: FOSUserBundle:Profile:show }
    
adherent:    
    path: adherent
    defaults: { _controller: CCIRamScoBundle:Yasmina:adherent }

adherent_liste:    
    path: admin/adherent/liste
    defaults: { _controller: CCIRamScoBundle:Yasmina:listeadherent }
    

admin:
    path: admin
    defaults: { _controller: CCIRamScoBundle:Yasmina:admin }
    
    
participant_add:    
    path: admin/participant/add
    defaults: { _controller: CCIRamScoBundle:Yasmina:addparticipant }
    
participant_liste:    
    path: admin/participant/liste
    defaults: { _controller: CCIRamScoBundle:Yasmina:listeparticipant }
    
participant_view:
    path: admin/participant/{id}
    defaults: { _controller: CCIRamScoBundle:Yasmina:view }
    
    
    
activite_add:    
    path: admin/activite/add
    defaults: { _controller: CCIRamScoBundle:Yasmina:addactivite }
           
activite_view:
    path: admin/activite/{id}
    defaults: { _controller: CCIRamScoBundle:Yasmina:view }
    requirements : 
        id: \d+



ramassage:
    path: ramassage
    defaults: { _controller: CCIRamScoBundle:Yasmina:ramassage }



